### ISSUE TITLE
Some Player Character Actors Unable to take Long Rest with Module Engaged

### ISSUE THREAD

**Issue by zero98205** [a-ws-m/FVTT-Long-Rest-HD-Healing-5e#9] opened 2022-11-20 04:19 UTC
Irrespective of the scene in question, a number of my player character actors are unable to take a Long Rest while the module is engaged. When I click Long Rest for them on their character sheets or with the HUD, the dialogue plays out, but the sidebar give no indication that anything has occurred, and expended hit points are not recharged, nor are LR enabled features activated, thus I must conclude that nothing happens.

I am unable to discern if there is a setting that would affect this as the sheets do not have a lot of visible dialogue or switches that I am aware of. Also, looking at the settings for the module, I cannot discern any way those settings would *selectively* affect player characters.

Of my players it's about 4/6 of the group that can't LR, but every single NPC that i've tested (about 35 of nearly 190) is capable of LR.

**Comment by MrZeyami** [comment] 2022-11-23 01:08
I've verified that this issue occurs after modifying my sorcerer's Font of Magic and Favored of the Gods class features to include uses that refresh on rest.

**Comment by a-ws-m** [comment] 2023-02-23 22:01
Sorry for the delay on following this up, would you be able to share your world(s) so I can reproduce this please?

**Comment by MrZeyami** [comment] 2023-02-23 22:06
Sorry, but I've long since found an alternate add-on, so I'm afraid sharing
the world wouldn't be helpful

**Comment by a-ws-m** [comment] 2023-02-23 22:24
OK, I'm confident it was probably the same issue as in #7 if it was only a few PCs, which should have been fixed by the latest release so I'm going to close this until it can be reproduced.

**Closed as completed by a-ws-m** 2023-02-23 22:24 UTC
